# Generated by Django 4.1.4 on 2022-12-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_now',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Текущая цена'),
        ),
    ]
