# Generated by Django 4.1.4 on 2022-12-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='products_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Количество товара'),
        ),
    ]
