# Generated by Django 4.1.4 on 2023-01-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
