# Generated by Django 4.1.4 on 2023-01-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Краткое описание'),
        ),
    ]
